spring:

  datasource:
    url: jdbc:mysql://vendor_db_mysql:3306/vendor_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: bp1234

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: none
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true
    format_sql: true

  flyway:
    enabled: true
server:
  port: 80