spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:33060}/${DB_DATABASE:vendor_db}?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:bp1234}

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: none
    hibernate:
      jdbc: time_zone = ${JPA_HIBERNATE_JDBC_TIME_ZONE:TimeZone}
    format_sql: ${JPA_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}


  flyway:
    enabled: ${FLYWAY_ENABLED:true}

server:
  port: ${SERVER_PORT:8085}

rabbitmq:
  queue:
    name: ${RABBITMQ_QUEUE_NAME:vendor-queue}
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME:vendor-exchange}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:vendor-routing-key}
