version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bp1234
      MYSQL_DATABASE: vendor_db

volumes:
  dbbase: