services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq_local"
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

volumes:
  rabbitmq_data:

networks:
  backend:
    external: true